name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: 'projects/865213359973/locations/global/workloadIdentityPools/castai-github-wif-pool/providers/castai-cluster-proportional-vert'
          service_account: 'image-writer-library@cicd-master-oxk5.iam.gserviceaccount.com'
          audience: 'https://cloud.google.com'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Artifact Registry
        env:
          REGISTRY: us-docker.pkg.dev/castai-hub/library/cpa
          VERSION: ${{ github.ref_name }}
        run: make manifest-list

      - name: Build and push to GHCR
        env:
          REGISTRY: ghcr.io/castai/images/cpa
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: make manifest-list
